import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./lib/provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Agu-Finance",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "AGU Finance | Best Financial Solutions for Africa's Professionals",
  description: "AGU Finance offers the best financial solutions tailored for Africa's professionals. Explore our services to manage and grow your wealth effectively.",
  keywords: "AGU Finance, financial solutions, Africa professionals, wealth management, financial services",
  openGraph: {
    title: "AGU Finance | Best Financial Solutions for Africa's Professionals",
    description: "Discover top-notch financial solutions designed for Africa's professionals with AGU Finance.",
    url: "https://agu-finance.vercel.app/",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AGU Finance | Best Financial Solutions for Africa's Professionals",
    description: "Explore AGU Finance's exceptional financial solutions tailored for Africa's professionals.",
    images: [
      {
        url: "https://agu-finance.vercel.app/your-image.jpg",
        alt: "AGU Finance"
      }
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
